return {
    ["Titanic Cat"] = "114",
    ["Titanic Atlantean Jellyfish"] = 0,
    ["Titanic Nightmare Cat"] = "568",
    ["Titanic Tiedye Dragon"] = "791",
    ["Titanic Tiedye Cat"] = "762",
    ["Titanic Jolly Cat"] = "506",
    ["Titanic Balloon Monkey"] = "606",
    ["Titanic Neon Agony"] = "643",
    ["Titanic Hubert"] = "885",
    ["Titanic Red Balloon Cat"] = "864",
    ["Titanic Blue Balloon Cat"] = "866",
    ["Titanic Hippomelon"] = "67",
    ["Titanic Dominus Astra"] = "972",
    ["Titanic Lucki"] = "912",
    ["Titanic Capybara"] = "946",
    ["Titanic Blobfish"] = "69",
    ["Titanic Hologram Cat"] = "756",
    ["Titanic Mystic Corgi"] = "596",
    ["banana"] = "2,988",
}
